[package]
name = "rusty-buggy-language-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rusty-buggy-language = { path = ".." }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "evaluate"
path = "fuzz_targets/evaluate.rs"
test = false
doc = false
bench = false
